# Generated by Django 5.2 on 2026-02-03 11:04

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=utils.random_filename)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.random_filename),
        ),
    ]
